name: Metrics

on:
  schedule:
    - cron: "0 0 * * *"   # Daily at midnight
  workflow_dispatch:        # Manual trigger bhi karo ek baar

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: SonamNarula
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
